sudo: false

git:
  submodules: false

cache:
  directories:
  - ~/perl5/
  - ~/.ccache

language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - dos2unix
            - libboost-all-dev
            - texinfo
            - texi2html
            - gdb
      env:
         - MATRIX_EVAL="CC=gcc && CXX=g++"

before_install:
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
    # other dependencies
  - eval "${MATRIX_EVAL}"
  - cpanm --local-lib=~/perl5 local::lib App::Prove Modern::Perl Capture::Tiny Capture::Tiny::Extended Path::Tiny File::Path Template Template::Plugin::YAML Test::Differences Text::Table CPU::Z80::Assembler Test::Cmd::Common Test::HexDifferences Data::HexDump Object::Tiny::RW Regexp::Common List::Uniq Clone
  - eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)

before_script:
  - export PATH=`pwd`/bin:$PATH
  - export ZCCCFG=`pwd`/lib/config
  - ulimit -c unlimited -S       # enable core
  - export BUILD_SDCC=1

script:
  - cd z88dk && ./build.sh -e -t

before_deploy:
  - tar -czf /tmp/z88dk-${TRAVIS_TAG}.tar.gz .

deploy:
  provider: releases
  file: /tmp/z88dk-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    tags: true
  api-key:
    secure: "eXrgElavEyC6Q+ujRdlTNQgsFCyyKSwrZv4pZ3viFTl8M77pcVWApP+cKR3Zu8SrVXI+DqrPcz5bH1zmIWcP18OFStGnBgTnj48r1v5K2kbQ6AVXH+j/yghp4a9fHs+Y25uyJFKFdUhF4VnnwEXJDKUdcEe0dx2Q6udMrWo0H3PVunFk3dGcjXAHwKOpz2PJEAX0rL3XOE1c60rrJRVK7kechnmHCQYkrZdQuHRlRKd1WQItEgLI0hTr0KLEy6ZpmT1leP0EeKHmvniqf3ZV2W5CWububGSyEyKNH7TBfq2swmD4TrLtJkZMng6CFz9o8RcPuz1ppo0GQbBXKXjSe6Unnr2PaziIhdm+2KWgS0+tzqJ0bL6fJR0eRDtAr4Bw6dLxY8GdNqVDUh6H4o3pEaSwxYB0OFaeBa9XdaUPaidXyK9xEevCOevY60a5xkueGXbr3JDViajS3hSg6S0jHuhRSvG8bwLO/jAduvNGqCELdjIJ+WBZ5jCs6wHe6JABLgoQ47a/USsMNwAhEz5LapaxeiuiaNltFG3kn3u396/g9DGTgYuCkMMdyW4YVJYzK0DiXWQIWHUCANzNu8gV9OOh1toy7uEgTFazim6nHROXVs0dpFBc0GG08Gh7gR0wuqHIXjHZWobCnMkoUl0PvNRahubabM4AiX96MRoT7zM="

notifications:
  email: false
